Store first and last search time and add filter options
mmgoodnow/cross-seed pull request #25
Opened 2020-11-12 03:27 UTC by craigjmidwinter

Not sure if this is what you had in mind for how to approach the timestamp filtering, but I thought I would take a stab at it.

2020-11-12 06:53 UTC, mmgoodnow requested changes
Wow, thanks so much! This is my first time receiving a PR and I really appreciate the work you've done :)

I've pointed out a few things I'd like to change before merging this into master. Would you mind if I hop in and make those changes? You could also do it if you'd like.

2020-11-12 06:53 UTC, mmgoodnow commented on src/index.js
> +	save(cacheKey, { firstSearched, lastSearched });
I think `existingTimestamps.firstSeen` should be `existingTimestamps.firstSearched`

2020-11-12 06:53 UTC, mmgoodnow commented on src/preFilter.js
> +	}
```suggestion
	if (
		excludeRecentSearch && 
		lastSearched > nMinutesAgo(excludeRecentSearch)
	) {
		logReason(...);
		return false;
	}
```

2020-11-12 06:53 UTC, mmgoodnow commented on src/cache.js
> +}
Good idea to migrate the old cache.

2020-11-12 06:53 UTC, mmgoodnow commented on src/cache.js
> +	return Object.keys(cache).includes(thing);
```suggestion
	return cache.hasOwnProperty(thing);
```

2020-11-12 14:15 UTC, craigjmidwinter commented
> Wow, thanks so much! This is my first time receiving a PR and I really appreciate the work you've done :)
> 
> I've pointed out a few things I'd like to change before merging this into master. Would you mind if I hop in and make those changes? You could also do it if you'd like.

Yeah all those changes make sense to me! I can try make them either later tonight or tomorrow evening, or if you have time and are wanting to jump in and make them to get it out, feel free!

2020-11-13 01:10 UTC, mmgoodnow commented
cool, go for it!

2020-11-15 02:26 UTC, craigjmidwinter commented
Updated as per your notes! The one exception being using the prototype field of hasOwnProperty since eslint forbids it.

2020-11-15 10:07 UTC, mmgoodnow reviewed
It's coming along nicely! Just a couple small things left.

2020-11-15 10:07 UTC, mmgoodnow commented on src/index.js
> +		: new Date().getTime();
super nit: can we change these to Date.now()?

2020-11-15 21:54 UTC, craigjmidwinter commented
Updated!

2020-11-15 22:01 UTC, mmgoodnow approved these changes
Great work, thanks for the contribution! I'll test this out this evening, and then merge the PR and update the README with the new options.

2020-11-16 03:16 UTC, merged